# docker compose  up --build --force-recreate utexas
name: project-utexas-arpanet
services:
  dec-20:
    build: ./
    image: dec-20
#    ports:
#      - "2030:2030"
    volumes:
      - type: bind
        source: ./dec-20
        target: /dec-20
    command: sh -c "cd dec-20 && ./pdp10-kl dsk-boot.ini"
# below leaves container with interactive terminal
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
    