; with following line simh ctrl-e becomes ctrl-\
set console wru=034
;set cpu hist=500000
set log -n go41.log
set lpt disable
set cpu 1024k kl10a
set tua rh20
set rpa rh20
set rpb rh20
set cty rsx20
;att lp20 -n prt.lst
set rpa0 rp06
set rpb1 rp06
at rpa0 dsk41/dsk0.rp06
at rpb1 dsk41/dsk1.rp06
att tty -U 2021
reset all
dep 0:100000 0
;at lp20 -n prt.log
load -c bts/boot.exb
expect "BOOT>" send "\r"; continue
expect "ENTER CURRENT DATE AND TIME:" send "APR-20-89 1212\r"; continue
expect "IS THIS CORRECT (Y,N)" send "Y\r"; continue
expect "WHY RELOAD?" send "SA\r"; continue
expect "CHECKD?" send "N\r"; continue
expect "[CONNECTED TO SUBJOB OPR(0)]" send -t after=20000 "\3"; continue
expect "\r\n@" send "login operator test\r"; continue
;expect "\r\n@" send "terminal la120\r"; continue
;expect "\r\n@" send "enable\r"; continue
;do test.do
cont


