set console wru=034
set cpu 1024k kl10b
set log -n instan.log
set tua rh20
set rpa rh20
set rpb rh20
set rpa0 rp06
set rpb1 rp06
set cty rsx20
at rpa0 dskan/dsk0.rp06
at rpb1 dskan/dsk1.rp06
att tty -U 2021

reset all
dep 0:100000 0
;at lp20 -n prt.log
load -c bts/boot.exb
cont


