set console wru=034
set cpu hist=5000000
set cpu 1024k kl10a
;set log -n kla.log
set env DSK=rpa
set env TAPE=tua
set env NAME=kl
set tua rh20
set rpa rh20
set rpb rh20
set rpa0 rp06
set rpb1 rp06
set cty rsx20
at tua -f e11 BB-5254D-BM.tap
at rpa0 -n dskan/dsk0.rp06
at rpb1 -n dskan/dsk1.rp06
load -c -b bts/mtboot.exb
expect "MTBOOT >" send "/l\r"; continue
cont
