; with following line simh ctrl-e becomes ctrl-\
set console wru=034
set log -n updt41.log
set lpt disable
set cpu 1024k kl10a
set tua rh20
set rpa rh20
set rpb rh20
set cty rsx20
set rpa0 rp06
set rpb1 rp06
;at tua -f e11 BB-5254D-BM.tap
;at tua -f e11 BB-4171H-BM.tap
at rpa0 dsk41/dsk0.rp06
at rpb1 dsk41/dsk1.rp06
att tty -U 2021
reset all
dep 0:100000 0
load -c bts/boot.exb
expect "BOOT>" send "\r"; continue
expect "ENTER CURRENT DATE AND TIME:" send "APR-20-89 1212\r"; continue
expect "IS THIS CORRECT (Y,N)" send "Y\r"; continue
expect "WHY RELOAD?" send "SA\r"; continue
expect "CHECKD?" send "N\r"; continue
expect "[CONNECTED TO SUBJOB OPR(0)]" send -t after=20000 "\3"; continue
expect "\r\n@" send "login operator test\r"; continue

expect "\r\n@" send "ENABLE\33"; continue
expect "(CAPABILITIES)" send "\r"; continue

;expect "\r\n$" send "dumper\r"; continue
;expect "DUMPER>" at tua0 -f e11 BB-5254D-BM.tap ; send "TAPE MTA0:\r"; continue
;expect "DUMPER>" send "rewind\r"; continue
;expect "DUMPER>" send "restore PS:<*>*.*.* <system>*.*.*\r"; continue
;expect "DUMPER>" send "exit\r"; continue

;expect "\r\n$" send "dumper\r"; continue
;expect "DUMPER>" at tua0 -f e11 BB-5254D-BM.tap ; send "TAPE MTA0:\r"; continue
;expect "DUMPER>" send "REWIND\r"; continue
;expect "DUMPER>" send "DEN 1600\r"; continue
;expect "DUMPER>" send "ACCOUNT SYS\r"; continue
;expect "DUMPER>" send "RESTORE PS:<*>*.*.* <NEW.SYSTEM>*.*.*\r"; continue
;expect "DUMPER>" send "EXIT\r"; continue

expect "\r\n$" send "dumper\r"; continue
expect "DUMPER>" at tua0 -r BB-4157F-BM_1983.tap ; send "TAPE MTA0:\r"; continue
expect "DUMPER>" send "REWIND\r"; continue
expect "DUMPER>" send "DEN 1600\r"; continue
expect "DUMPER>" send "ACCOUNT SYS\r"; continue
expect "DUMPER>" send "RESTORE PS:<*>*.*.* <NEW.SYSTEM>*.*.*\r"; continue
expect "DUMPER>" send "EXIT\r"; continue
                                                                   
expect "\r\n$" send "CONNECT\33"; continue
expect "(TO DIRECTORY)" send "ps:<system>\r"; continue
expect "\r\n$" send "COPY\33" ;continue
expect "(FROM)" send "AN-MONSML.EXE\33"; continue
expect "(TO)" send "MONITR.EXE\r"; continue

cont


