set console wru=034
set cpu hist=5000000
set cpu 1024k kl10a
set log -n kla.log
set env DSK=rpa
set env TAPE=tua
set env NAME=kl
#set tua debug=cono;dataio;detail;data;coni
#set rpa debug=cono;dataio;detail;data;coni;exp
#set rpb debug=cono;dataio;detail;data;coni;exp
#set cty debug=cono;dataio;detail;coni;data
#set cpu debug=irq
set tua rh20
set rpa rh20
set rpb rh20
set rpa0 rp06
set rpb1 rp06
set cty rsx20
# Tops 20 V4.1 KLA
at tua -f e11 tapes/BB-4171H-BM.tap
# Tops 20 V4 2040 - bad
#at tua -f e11 tapes/BB-4171G-BM.tap
# Tops 20 V4 AN
#at tua -f e11 tapes/BB-5254D-BM.tap
# Tops 20 2060
#at tua -f e11 tapes/BB-H137B-BM.tap
at rpa0 -n dsk/kla_psv4_10.rp06
at rpb1 -n dsk/kla_psv4_11.rp06
load -c -b bts/mtboot.exb
;set debug -n /tmp/ka.log
;expect "BUG" echo "history\r" ; show @kadsk cpu hist; quit
expect "MTBOOT >" send "/l\r"; continue
expect "MTBOOT >" send "/g143\r"; continue
expect "DO YOU WANT TO REPLACE THE FILE SYSTEM ON THE PUBLIC STRUCTURE?"  send -t delay=10000 "Y\r"; continue
expect "DO YOU WANT TO DEFINE THE PUBLIC STRUCTURE?" send -t delay=100000 "Y\r"; continue
expect "HOW MANY PACKS ARE IN THIS STRUCTURE:" send -t delay=100000 "2\r"; continue
expect "ON WHICH \"CHANNEL,UNIT\" IS LOGICAL PACK # 0 MOUNTED:" send -t delay=100000 "0,0\r"; continue
expect "ON WHICH \"CHANNEL,UNIT\" IS LOGICAL PACK # 1 MOUNTED:" send -t delay=100000 "1,1\r"; continue
expect "DO YOU WANT THE DEFAULT SWAPPING SPACE?" send -t after=10000 delay=100000  "Y\r"; continue
expect "DO YOU WANT THE DEFAULT SIZE FRONT END FILE SYSTEM?" send -t after=10000 delay=100000  "Y\r"; continue
expect "DO YOU WANT THE DEFAULT SIZE BOOTSTRAP AREA?" send -t after=10000 delay=100000 "Y\r"; continue
expect "DO YOU WANT TO WRITE A SET OF PROTOTYPE BAT BLOCKS?" send -t after=100000 delay=100000 "Y\r"; continue
expect "DO YOU WANT TO WRITE A SET OF PROTOTYPE BAT BLOCKS?" send -t after=100000 delay=100000 "Y\r"; continue
expect "NO SYSJOB" send -t after=1000000 "\3"; continue
expect "MX>" send "G"; continue
expect "ET FILE" send "MTA0:\r"; continue
expect "MX>" send "G"; continue
expect "ET FILE" send "MTA0:\r"; continue
expect "MX>" send "S\r"; continue
expect "@" send "ENABLE\33"; continue
expect "(CAPABILITIES)" send "\r"; continue

expect "$" send "run\33"; continue
expect "(PROGRAM)" send "mta0:\r"; continue
expect "DLUSER>" send "load\33"; continue
expect "(FROM FILE)" send "mta0:\r"; continue
expect "DLUSER>" send "exit\r"; continue

expect "$" send "run\33"; continue
expect "(PROGRAM)" send "mta0:\r"; continue
expect "DUMPER>" send "tape\33"; continue
expect "(DEVICE)" send "mta0:\r"; continue

expect "DUMPER>" send "restore\33"; continue
expect "(TAPE FILES)" send "PS:<*>*.*.* <sys\33"; continue
expect "*.*.*" send "\r"; continue

expect "DUMPER>" send "restore\33"; continue
expect "(TAPE FILES)" send "PS:<*>*.*.* <sub\33"; continue
expect "*.*.*" send "\r"; continue

expect "DUMPER>" send "restore\33"; continue
expect "(TAPE FILES)" send "PS:<*>*.*.* <uetp.lib>\33"; continue
expect "*.*.*" send "\r"; continue
expect "DUMPER>" send "EXIT\r"; continue

expect "\r\n$" send "CONNECT\33"; continue
expect "(TO DIRECTORY)" send "ps:<system>\r"; continue

expect "\r\n$" send "COPY\33" ;continue
expect "(FROM)" send "MONSML.EXE\33"; continue
expect "(TO)" send "MONITR.EXE\r"; continue

expect "\r\n$" send "COPY\33"; continue
expect "(FROM)" send "TTY:\33"; continue
expect "(TO)" send "MONNAM.TXT\r"; continue
expect "TTY:"; continue
expect "TTY:" send -t after=10000 "Installation-test V4.1\r\32"; continue

expect "\r\n$" send "CREATE\33"; continue
expect "(FILE)" send "4-1-config.cmd\r"; continue
expect "00100" send "terminal 1-20 speed 9600\r"; continue
expect "00200" send "define new: ps:<new>,sys:\r"; continue
expect "00300" send "define old: ps:<old>,sys:\r"; continue
expect "00400" send "define hlp: sys:\r"; continue
expect "00500" send "magtape 0 17 tu45\r"; continue
expect "00600" send "printer 0 lowercase vfu sys:normal.vfu\r"; continue
expect "00700" send "printer 0 lowercase ram sys:lp96.ram\r"; continue
expect "00800" send "timezone 5\r"; continue
expect "00900" send "disable account-validation\r"; continue
expect "01000" send "\33"; continue
expect "\r\n*" send "e\r"; continue

expect "\r\n$" send "\5create\33"; continue
expect "(DIRECTORY NAME)" send "<operator>\r"; continue
expect "\r\n$" send "pass\33test\r"; continue
expect "\r\n$" send "user-group 100\r"; continue
expect "\r\n$" send "\r"; continue

expect "\r\n$" send "\5create\33"; continue
expect "(DIRECTORY NAME)" send "<remarks>\r"; continue
expect "\r\n$" send "\r"; continue

expect "\r\n$" send "connect\33"; continue
expect "(TO DIRECTORY)" send "ps:<subsys>\r"; continue

expect "\r\n$" send "CREATE\33"; continue
expect "(FILE)" send "lpform.ini\r"; continue
expect "00100" send "normal/banner:2/header:2/trailer:2\r"; continue
expect "00200" send "narrow/banner:2/header:2/trailer:2/width:72\r"; continue
expect "00300" send "\33"; continue
expect "\r\n*" send "eu\r"; continue
expect "\r\n$" send "\5CEASE +1\r"; continue
expect "Shutdown" 
cont
#expect "BOOT>" send "\r"; continue
#expect "ENTER CURRENT DATE AND TIME:" send "APR-20-89 1212\r"; continue
#expect "IS THIS CORRECT (Y,N)" send "Y\r"; continue
#expect "WHY RELOAD?" send "SA\r"; continue
#expect "CHECKD?" send "N\r"; continue
#expect "[CONNECTED TO SUBJOB OPR(0)]" send -t after=20000 "\3"; continue
#expect "\r\n@" send "login operator test\r"; continue
#expect "\r\n@" send "terminal la120\r"; continue
#expect "\r\n@" send "enable\r"; continue
#do fort.do
#do cobol.do
#do algol.do
#do dbms.do
#reset all
#dep 0:100000 0
#at lp20 -n prt.log
#load -c bts/boot.exb
#cont

